#pragma once

enum ESPI_ERROR_CODE
{
	ESPI_ERROR_CODE_FIRST_WSCEnumProtocols_FAILED =10000,
	ESPI_ERROR_CODE_GlobalAlloc_FAILED,
	ESPI_ERROR_CODE_SECOND_WSCEnumProtocols_FAILED,
	ESPI_ERROR_CODE_NOT_FIND_APPROPRIATE_PROTOCOL,
	ESPI_ERROR_CODE_INSTALL_LAYERED_PROTOCOL_FAILED,
	ESPI_ERROR_CODE_NOT_FIND_INSTALLED_PROTOCOL,
	ESPI_ERROR_CODE_INSTALL_PROTOCOL_CHAIN_FAILED,
	ESPI_ERROR_CODE_ADJUST_SEQUEESE_FAILED,

};